const fs = require('fs');

const path = 'd:/project/one-api/daof-ai-hub/i18n/en-US.json';
let raw = fs.readFileSync(path, 'utf8');
let json = JSON.parse(raw);

const replacements = {
    'Initializing Core Framework...': 'Initializing System...',
    'Accept & Exit Lobby': 'Confirm & Exit',
    'Channel Hubs': 'Channels',
    'Global Token Matrix': 'API Token Management',
    'Manage sub-tokens and monitor all proxy behaviors executed through your account.': 'Manage access tokens and monitor proxy logs.',
    'Distribution Matrix': 'Token Distribution',
    'Compute Radar': 'Usage Logs',
    'Untitled Node Token': 'Untitled Token',
    'Permanently incinerate this access credential? All dependent systems will lose connection immediately!': 'Permanently delete this token? All associated systems will lose connection!',
    'Credential successfully extracted!': 'Token copied successfully!',
    'Generate Command Domain': 'Manage Access Tokens',
    'Create independent API Keys for secure client and proxy invocation.': 'Create separate API Keys to track usage for different applications.',
    'Forging...': 'Creating...',
    'Syncing Matrix...': 'Syncing Data...',
    'Active Engine': 'Active',
    'Digital Token': 'API Key',
    'Burned Quota': 'Used Quota',
    'Microscopic Log Radar': 'Token Audit Logs',
    'Compute fuel logs will appear here once the stream proxy engine routes requests.': 'Proxy call logs will be displayed here.',
    'Scanning deep space logs...': 'Loading logs...',
    'No activity detected in the deep space channel yet.': 'No audit logs found.',
    'Quantum Model': 'AI Model',
    'Root Auth': 'Master Token',
    'Burn Rate ($)': 'Cost ($)',
    'WARNING: Updating will log out your current admin session!\\nAnd your admin panel suffix will permanently lock to ?sys={{username}}\\n\\nAre you sure you want to forcibly override the profile?': 'Warning: Updating will change your admin login path to ?sys={{username}} and log you out. Continue?',
    'Update completed and matrix synced!': 'Settings saved successfully!',
    'New Enrty Point: /?sys={{username}}': 'New Login Path: /?sys={{username}}',
    'Scanning vital signs...': 'Retrieving profile...',
    'Personal Digital Profile (Profile)': 'Admin Profile',
    'Unique Execution Code (Username)': 'Login Username',
    'Current Tier (Role)': 'Account Role',
    'Supreme Commander (Admin)': 'System Administrator',
    'Civilian (User)': 'Standard User',
    'High-Dimensional Permission Override (Root Override)': 'Admin Credentials',
    "Here you can directly interfere with the system's lowest level admin profile. Use with caution: changing the username will instantly mutate your exclusive admin URL!": "You can change your super admin login credentials here. Note: Changing your username will modify your default admin access URL.",
    'Enter new global username': 'Enter new username',
    'Enter new override password': 'Enter new password',
    'Overwriting Core...': 'Saving...',
    'Exercise Supreme Power, Tamper Directive': 'Save Changes',
    'Only 2-20 valid characters allowed': 'Only 2-20 alphanumeric characters allowed',
    'Network fetch anomaly during config': 'Network error during configuration',
    'Network verification anomaly': 'Network error during verification',
    'Communication anomaly': 'Network communication error',
    'Verifying holographically...': 'Verifying...',
    'Branding matrix...': 'Creating Account...',
    'Initiating authorization with DaoF means you agree to the Terms of Service': 'By registering or logging in, you agree to our Terms of Service',
    'Network blocked, core engine unresponsive': 'Network error or server unreachable.',
    'Initial Security Constraints': 'Initial Deployment Setup',
    'To ensure system physical security, you must immediately change your credentials. System entry will permanently bind to this new identity.': 'Welcome. Please set your own admin account and password. You will use these credentials to log in hereafter.',
    'Set New Command Axis (Username)': 'Set Admin Username',
    'Avoid easily guessable words': 'Use unique identifiers',
    'Set High-Entropy Code (Password)': 'Set Admin Password',
    'Overwriting globally...': 'Saving Configuration...',
    'Confirm & Lock Core': 'Save & Apply',
    'Verification Code Issuance': 'Enter Password',
    'Access Supreme Power': 'Login to Dashboard',
    'God Mode': 'User Management',
    'Anti-Fraud Risk Policy': 'Risk & Registration Policy',
    'Manage core system parameters related to global exchange rates and underlying billing. THIS AFFECTS THE ENTIRE SYSTEM!': 'Manage global exchange rates and billing configurations.',
    '[SECURE ZONE] The underlying AES-256-GCM engine will intercept and encrypt your keys here.': '[SECURE AREA] System encrypts and stores your keys securely.',
    'Unified Callback Addressing': 'Unified Callback URL',
    'Aliyun SMS Anti-Fraud Gateway': 'Aliyun SMS Gateway',
    'Build a solid defense line against mass abusers. Set threshold limits to intercept suspected bulk requests and force deep verification (SMS binding).': 'Configure risk control policies against malicious bulk registration. Enforce SMS validation upon reaching IP thresholds.',
    'Registration Access Strategy': 'Registration Risk Policy',
    'Determines the default trust level for external visitors on the frontend system': 'Determines the verification strictness for new registrations.',
    'Ultimate Experience (No phone needed, recommended for internal geeks)': 'Permissive (No phone verification required)',
    'Sandbox Intelligence (Elastic pop-up based on IP reputation)': 'Dynamic (SMS verification upon reaching IP limits)',
    'Ultimate Purification (All registrations force phone verification)': 'Strict (All registrations require SMS verification)',
    'IP Hotspot Tolerance Threshold': 'IP Reputation Tolerance Limit',
    "Under 'Sandbox Intelligence' mode, when accounts registered from the same IP exceed this number, it is marked as 'high-risk', forcibly blocking passwordless flow.": "Under Dynamic Mode, when signups from the same IP exceed this limit, SMS verification will be enforced.",
    'Writing Holographically...': 'Saving...',
    'User Profiles & Risk Control Dispatch Center': 'User Management Center',
    'Manage all access nodes within the matrix network. Identify, interfere, and completely sever the model flow of malicious users during high risk.': 'Manage all registered users and their API quotas across the platform.',
    'Identity Beacon (ID / Name)': 'System Name (ID)',
    'Entity Connector (Binding)': 'Auth Binding',
    'Matrix Access Period (Reg Time)': 'Registration Date',
    'Allowed Compute Quota (Quota)': 'API Free Quota',
    'Traffic Status (Status)': 'Status',
    'Manipulation (Actions)': 'Actions',
    'Retrieving data from the Sea of Memory...': 'Fetching data from server...',
    'No matching entities retrieved yet': 'No matched data found.',
    'Holographically Banned': 'Banned',
    'Space-Time Audit Stream': 'Audit Logs',
    'Tamper Parameters': 'Edit Profile',
    'Physical Eradication': 'Delete Permanently',
    'Are you sure you want to dimensionally cleanse this personnel? This action is irreversible!': 'Are you sure you want to permanently delete this user? This action cannot be undone!',
    'Entity Audit Traceability': 'Audit Trace',
    'Searching time stream...': 'Searching database...',
    'This digital shell currently has no historical risk operation records.': 'No audit logs found for this user.',
    'Force Create Profile': 'Admin Add User',
    'Data Modification': 'Update Information',
    'Initialized user [{{target}}] into the digital network. Initial quota: [${{quota}}]': 'Created new user [{{target}}] with quota [${{quota}}].',
    'Completely deleted [{{target}}] from the database.': 'Deleted user [{{target}}] permanently.',
    'Force Issue New Pass': 'Add New User',
    'Tamper Account Profile': 'Edit User Information',
    'Confirm Exercise of Power': 'Confirm Action',
    'Manage all upstream sources and independently control the tiered price parameters mapped underneath them': 'Manage upstream providers and independently configure pricing structures for specific models.',
    'Equip New Tunnel': 'Add Provider',
    'Search upstream via type...': 'Search provider type...',
    'Origin Type': 'Provider Type',
    'Custom Proxy Gateway': 'Custom Base URL',
    'Priority Weight': 'Route Weight',
    'Command Hub': 'Actions',
    'Prices & Models': 'Models & Pricing',
    'Deploy new channel tunnel': 'Add Provider',
    'Re-calibrate channel': 'Edit Provider',
    'Load weight (higher is greedier)': 'Load weight (higher = more traffic)',
    'Lock Settings': 'Save Settings',
    'Fetch Public Models from Upstream Channel': 'Fetch Models from Provider',
    'Automatically detect native model list from upstream {{type}}, batch import to skip manual input.': 'Automatically fetch available models from upstream {{type}} gateway to avoid manual entry.',
    'Probing /models list configured at gateway node...': 'Fetching /models list from gateway...',
    'No available model list detected. Check request headers or if provider blocked probe endpoint.': 'No models found. Provider might block the /models endpoint.',
    'Shatter the data channel permanently? This will destroy all sub-pricing constraints!': 'Permanently delete this provider and its associated pricing models?',
    'Mount New Price Matrix': 'Add Model Price',
    'Model Binding ID': 'Model ID',
    'Visual Tag': 'Display Name',
    'Local Weight': 'Weight',
    'Base Flow ($/1M)': 'Base Pricing ($/1M)',
    'Tiered Controls': 'Tiered Pricing',
    'Execution': 'Actions',
    'Override Internal Pricing': 'Configure Model Price',
    'Fine-Tune Tier Bounds': 'Edit Configuration',
    'Human Visual Tag': 'Display Name',
    'Signal Probability': 'Routing Weight',
    'Input Drop ($/1M Tokens)': 'Input Price ($/1M)',
    'Output Result ($/1M Tokens)': 'Output Price ($/1M)',
    'Panic Limit Bounds (0 means disabled)': 'High Concurrency & Long Context Rate (0 to disable)',
    'Token Length Cutoff Threshold': 'Context Threshold',
    'Punishment Input Load ($/1M)': 'Tier Input Price ($/1M)',
    'Punishment Base Gen ($/1M)': 'Tier Output Price ($/1M)',
    'Cease': 'Cancel',
    'Commit Force': 'Save Config',
    'Purge specific model rule structure assigned to this channel?': 'Remove this model configuration from the selected provider?',
    'Forge New Model': 'Configure New Model',
    'Risk Tier Mechanism (0 for off)': 'Tier Pricing Settings (0 for off)',
    'Are you sure you want to eradicate this model rule from the matrix?': 'Are you sure you want to remove this model?',
    'Polymorphic Context Management Library': 'System Language Management',
    "Covering the entire site's text components, instantly disperse new internationalization branches by injecting a newly architected JSON black box. (zh-CN/en-US belong to the core dictionary, exempt from death)": "Manage interface languages by uploading structured JSON files. Core dictionaries (zh-CN/en-US) cannot be deleted.",
    'Inject New Dict Stream (.json)': 'Upload Language Pack (.json)',
    'Upload network shattered': 'Upload connection failed.',
    'Absolutely erase language pack [{{langId}}] data?': 'Permanently delete language pack [{{langId}}]?',
    'Thoroughly wiped out this language dictionary': 'Language pack deleted successfully.',
    'Context Primary Key (ID)': 'Language ID',
    'General Display Name': 'Display Name',
    'Dict Topology Size': 'File Size',
    'Manipulation & Audit': 'Actions',
    'No context slices exist.': 'No extra language packs found.',
    'Submerge Copy Source Block': 'Download JSON',
    'Omnipotent Model Manager': 'Model Gateway Manager',
    'Core Model Matrix Pool': 'Model Availability Pool',
    'Payload parsing exception': 'Invalid payload format.',
    'Instruction source not found': 'Target endpoint not found.',
    'Auth verification crashed, entrance sealed': 'Authentication failed, incorrect password.',
    'New instruction set contains security vulnerabilities': 'Invalid request parameters submitted.',
    "Cannot use raw alias 'root', establish a unique commander alias.": "Cannot use 'root'. Please choose a secure username.",
    'Underlying auth matrix overwrite failed, possible entity conflict.': 'Failed to save admin profile, possible username conflict.',
    'JSON matrix deserialization failed, format may be corrupted': 'JSON deserialization failed, corrupted format.',
    'Language pack branding to disk failed': 'Failed to save language pack disk.',
    'Root language packs (zh-CN/en-US) shielded by core logic, cannot be erased': 'System core language packs cannot be deleted.',
    'Language pack annihilation failed or missing': 'Failed to delete language pack.',
    'Invalid code payload': 'Invalid OAuth code.',
    'Admin has not initialized GitHub auth service': 'GitHub Authentication not configured by admin.',
    'GitHub profile anomaly': 'Failed to fetch GitHub profile.',
    'System verdict: Phone number already bound to another account': 'Phone number is already bound to another account.',
    'Creating root record failed': 'Failed to create root admin record.',
    'Illegal nickname format! Only 2-20 Chinese, English, numeric or underscore characters allowed': 'Invalid username format.',
    'System anti-spam verdict: This Github account is already registered': 'This GitHub account is already registered.',
    'Creating pass record failed': 'Failed to create user record.',
    'Underlying record casting failed': 'Database insertion failed.',
    'Derivative credential distribution complete': 'API Token generated successfully.',
    'Token entity lost': 'Token not found.',
    'Entity is not under your control domain': 'You do not have permission for this user/channel.',
    'Channel cut off, credential completely incinerated': 'API Token deleted successfully.',
    'Failed to fetch data matrix': 'Failed to fetch data list.',
    'Name is the foundation of survival, cannot be empty': 'Name cannot be empty.',
    'Alias conflict! Nickname already forged': 'Username is already taken.',
    'Account instantiation in root matrix failed': 'Account creation failed.',
    'Node has disappeared': 'User profile not found.',
    'Suicide module intervened: Cannot seal the last swordholder!': 'System Protection: Cannot ban the last active administrator!',
    'Suicide module intervened: Cannot eradicate the last guardian!': 'System Protection: Cannot delete the last active administrator!',
    'Update failed, target may have conflict': 'Update failed, possible validation conflict.',
    'Name forging complete!': 'Name saved successfully!',
    'Update complete and synchronized across all nodes!': 'Configuration updated successfully!',
    'This digital profile has been permanently banned': 'This account has been banned due to violations.',
    'Sandbox security policy initiated. Your GitHub credentials are locked. Please complete SMS verification.': 'Security policy enforced. Please verify your phone number to proceed.',
    'Secure credentials detected. Please set your exclusive application nickname.': 'Please enter a display name to complete registration.',
    'Configuration wrapped with AES-GCM and securely saved. Global routing cache restarted.': 'System configuration successfully updated.',
    'God-level clearance approved.': 'Administrator login successful.',
    'Protocol refresh successful, global lockdown lifted.': 'Initial setup complete, transferring to dashboard.',
    'Holographic admin profile re-architected successfully! Notice: Due to the alias change, you will now be logged out. Please securely authenticate using your new alias.': 'Admin alias updated. You will be logged out. Please log in using your new alias.',
    'Supreme command token missing': 'Access Denied: Administrator privileges required.',
    'Forged instruction, unauthorized access denied': 'Request denied or unauthorized status.',
    'Physical-layer ward: System detected you are on an external network. Dark web channel entry blocked.': 'Access Denied: Admin panel is restricted to the local network (LanGuard).',
    'System Not Ready': 'System Initialization Not Complete',
    'Cryptographic core not initialized': 'Cryptographic module not initialized',
    'Ciphertext length below security standard': 'Password length below security standards.',
    'Forbidden to erase system core framework language': 'Core languages cannot be deleted.',
    'Missing critical model binding identifier': 'Missing model identifier.',
    'Failed to fuse model parameters into active channel': 'Failed to add model to target channel.',
    'Target binding matrix configuration vanished': 'Target channel not found.',
    'Failed to reconstruct price logic on the fly': 'Failed to update pricing.',
    'Unable to decrypt base channel configuration': 'Failed to fetch channel config.',
    'Construction of new tunnel line utterly failed': 'Failed to create provider channel.',
    'Upstream source node lost signal': 'Provider channel not found.',
    'Failed to update channel matrix routing': 'Failed to update provider config.',
    'Destruction of base channel failed': 'Failed to delete provider channel.',
    'This underlying model ID is already occupying the gateway': 'This model ID already exists.',
    'Target model vanished': 'Target model not found.',
    'Model configuration injected into deep space matrix': 'Model configuration saved.',
    'Model rule completely stripped': 'Model deleted successfully.'
};

function processObj(obj) {
    if (typeof obj === 'string') {
        let str = obj;
        for (let k in replacements) {
            str = str.split(k).join(replacements[k]);
        }
        return str;
    } else if (Array.isArray(obj)) {
        return obj.map(item => processObj(item));
    } else if (typeof obj === 'object' && obj !== null) {
        let newObj = {};
        for (let k in obj) {
            newObj[k] = processObj(obj[k]);
        }
        return newObj;
    }
    return obj;
}

const cleanedJson = processObj(json);
fs.writeFileSync(path, JSON.stringify(cleanedJson, null, 2), 'utf8');
console.log("English JSON Translation Purified Successfully!");
